/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewBookingRouteImport } from './routes/new-booking'
import { Route as MyVehicleRouteImport } from './routes/my-vehicle'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DriverLoadsRouteImport } from './routes/driver-loads'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AccountRoute = AccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AnalyticsRoute = AnalyticsRouteImport.update({ id: '/analytics', path: '/analytics', getParentRoute: () => rootRouteImport } as any)
const ClientRoute = ClientRouteImport.update({ id: '/client', path: '/client', getParentRoute: () => rootRouteImport } as any)
const DriverLoadsRoute = DriverLoadsRouteImport.update({ id: '/driver-loads', path: '/driver-loads', getParentRoute: () => rootRouteImport } as any)
const DriverRoute = DriverRouteImport.update({ id: '/driver', path: '/driver', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const HomeRoute = HomeRouteImport.update({ id: '/home', path: '/home', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const MyBookingsRoute = MyBookingsRouteImport.update({ id: '/my-bookings', path: '/my-bookings', getParentRoute: () => rootRouteImport } as any)
const MyVehicleRoute = MyVehicleRouteImport.update({ id: '/my-vehicle', path: '/my-vehicle', getParentRoute: () => rootRouteImport } as any)
const NewBookingRoute = NewBookingRouteImport.update({ id: '/new-booking', path: '/new-booking', getParentRoute: () => rootRouteImport } as any)
const ProfileRoute = ProfileRouteImport.update({ id: '/profile', path: '/profile', getParentRoute: () => rootRouteImport } as any)
const RegisterRoute = RegisterRouteImport.update({ id: '/register', path: '/register', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const SupportRoute = SupportRouteImport.update({ id: '/support', path: '/support', getParentRoute: () => rootRouteImport } as any)
const TrackRoute = TrackRouteImport.update({ id: '/track', path: '/track', getParentRoute: () => rootRouteImport } as any)
const WalletRoute = WalletRouteImport.update({ id: '/wallet', path: '/wallet', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/client': typeof ClientRoute
  '/driver': typeof DriverRoute
  '/driver-loads': typeof DriverLoadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-vehicle': typeof MyVehicleRoute
  '/new-booking': typeof NewBookingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRoute
  '/wallet': typeof WalletRoute
}

export interface FileRoutesByTo extends FileRoutesByFullPath {}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/client': typeof ClientRoute
  '/driver': typeof DriverRoute
  '/driver-loads': typeof DriverLoadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/my-vehicle': typeof MyVehicleRoute
  '/new-booking': typeof NewBookingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRoute
  '/wallet': typeof WalletRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/admin' | '/analytics' | '/client' | '/driver' | '/driver-loads' | '/forgot-password' | '/home' | '/login' | '/my-bookings' | '/my-vehicle' | '/new-booking' | '/profile' | '/register' | '/signup' | '/support' | '/track' | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/admin' | '/analytics' | '/client' | '/driver' | '/driver-loads' | '/forgot-password' | '/home' | '/login' | '/my-bookings' | '/my-vehicle' | '/new-booking' | '/profile' | '/register' | '/signup' | '/support' | '/track' | '/wallet'
  id: '__root__' | '/' | '/account' | '/admin' | '/analytics' | '/client' | '/driver' | '/driver-loads' | '/forgot-password' | '/home' | '/login' | '/my-bookings' | '/my-vehicle' | '/new-booking' | '/profile' | '/register' | '/signup' | '/support' | '/track' | '/wallet'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ClientRoute: typeof ClientRoute
  DriverRoute: typeof DriverRoute
  DriverLoadsRoute: typeof DriverLoadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  MyVehicleRoute: typeof MyVehicleRoute
  NewBookingRoute: typeof NewBookingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TrackRoute: typeof TrackRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/account': { id: '/account'; path: '/account'; fullPath: '/account'; preLoaderRoute: typeof AccountRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/analytics': { id: '/analytics'; path: '/analytics'; fullPath: '/analytics'; preLoaderRoute: typeof AnalyticsRouteImport; parentRoute: typeof rootRouteImport }
    '/client': { id: '/client'; path: '/client'; fullPath: '/client'; preLoaderRoute: typeof ClientRouteImport; parentRoute: typeof rootRouteImport }
    '/driver': { id: '/driver'; path: '/driver'; fullPath: '/driver'; preLoaderRoute: typeof DriverRouteImport; parentRoute: typeof rootRouteImport }
    '/driver-loads': { id: '/driver-loads'; path: '/driver-loads'; fullPath: '/driver-loads'; preLoaderRoute: typeof DriverLoadsRouteImport; parentRoute: typeof rootRouteImport }
    '/forgot-password': { id: '/forgot-password'; path: '/forgot-password'; fullPath: '/forgot-password'; preLoaderRoute: typeof ForgotPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/home': { id: '/home'; path: '/home'; fullPath: '/home'; preLoaderRoute: typeof HomeRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/my-bookings': { id: '/my-bookings'; path: '/my-bookings'; fullPath: '/my-bookings'; preLoaderRoute: typeof MyBookingsRouteImport; parentRoute: typeof rootRouteImport }
    '/my-vehicle': { id: '/my-vehicle'; path: '/my-vehicle'; fullPath: '/my-vehicle'; preLoaderRoute: typeof MyVehicleRouteImport; parentRoute: typeof rootRouteImport }
    '/new-booking': { id: '/new-booking'; path: '/new-booking'; fullPath: '/new-booking'; preLoaderRoute: typeof NewBookingRouteImport; parentRoute: typeof rootRouteImport }
    '/profile': { id: '/profile'; path: '/profile'; fullPath: '/profile'; preLoaderRoute: typeof ProfileRouteImport; parentRoute: typeof rootRouteImport }
    '/register': { id: '/register'; path: '/register'; fullPath: '/register'; preLoaderRoute: typeof RegisterRouteImport; parentRoute: typeof rootRouteImport }
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/support': { id: '/support'; path: '/support'; fullPath: '/support'; preLoaderRoute: typeof SupportRouteImport; parentRoute: typeof rootRouteImport }
    '/track': { id: '/track'; path: '/track'; fullPath: '/track'; preLoaderRoute: typeof TrackRouteImport; parentRoute: typeof rootRouteImport }
    '/wallet': { id: '/wallet'; path: '/wallet'; fullPath: '/wallet'; preLoaderRoute: typeof WalletRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AccountRoute,
  AdminRoute,
  AnalyticsRoute,
  ClientRoute,
  DriverRoute,
  DriverLoadsRoute,
  ForgotPasswordRoute,
  HomeRoute,
  LoginRoute,
  MyBookingsRoute,
  MyVehicleRoute,
  NewBookingRoute,
  ProfileRoute,
  RegisterRoute,
  SignupRoute,
  SupportRoute,
  TrackRoute,
  WalletRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
